apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  labels:
    type: local
    app: odoo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
